### ISSUE TITLE
Deployment refactor

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/FingerprintSecureDrop#84]
**Note:** I started rewriting this issue as I worked on the refactor, but realized I'm just too sick of devops to do this right now. What's below won't make sense because it's been chopped and screwed. Will fix it sometime in the future.

Currently we have one role, crawler, the `tasks/main.yml` of which looks approximately as follows:

```

---
# Isolates the config tasks into logical groups, in case the
# config should be broken out across multiple hosts. Vars are shared
# across all of these tasks (e.g. the crawler service needs database
# credentials), so bundling them all within the same role.

- include: set-environment-variables.yml
  when: fpsd_database_configure_credentials == true
  tags: database

- include: configure-databases.yml
  when: fpsd_database_initialize_local_db == true
  tags: database

- block:
  - include: packages.yml
  - include: configure.yml
  - include: download-verify-tbb.yml
  - include: download-verify-tor.yml
  - include: build-install-tor.yml
  - include: install-systemd-unit.yml
  when: fpsd_crawler_configure_service == true
```

New:

```
- include: db-packages-and-init.yml
  tags:
    - db
    - db-pkgs
- include: db-configure.yml
  tags:
    - db
    - db-configure
- include: fpsd-apt-deps.yml
- include: fpsd-system-setup.yml
- include: fpsd-repo.yml
- include: fpsd-py-deps.yml
- include: fpsd-tor.yml
- include: fpsd-tbb.yml
- include: install-systemd-unit.yml
- include: dev-packages.yml
```

`db-packages-and-init.yml` would install the correct version of PostgreSQL and the necessary extensions (including psycopg2, needed by Ansible). It would make sure the right version cluster was running, and a Postgres server has been started running with some data directory and logfile (the location of these last two objects is unimportant). `db-configure.yml` would create the necessary (Postgres) roles, schemas, and tables. It would run entirely as the `postgres` user, and never set any environment variables, or create any `PGPASSFILE`s.

`dev-packages.yml` would include things like `tmux` and `ipython`, while `apt-deps.yml` would include only the required packages for building Tor, running the fpsd code, and connecting to a database. Each tasklist will be tagged so that, e.g., `dev-packages.yml` could be skipped in Travis. `fpsd_database_configure_credentials.yml` would be subsumed into `configure.yml`, since it's an integral part of configuration that should always be run. In this role, everyone who is in the `fpsd_users` var should be added to the `fpsd` group for directory access (#78), and have a `PGPASSFILE` generated for themselves.

Each tasklist will be tagged, so that, e.g., we can skip `db-packages-and-init.yml` in Travis because it's an extremely finicky environment, and Postgres stuff there is better handled in the `before_script:` section of `.travis.yml`.

I believe if we use the same var names in the two roles, we can, e.g., have a single var define the (Postgres) roles that get created in the Database role, and the users who get a PGPASSFILE instantiated in their homedir and added to the `fpsd` Linux system group.
